name: XRCPracticeByChifou
author: chifou
version: 1.0
main: com.chifou.xrc.Main
commands:
  practicehelp:
    description: permit to get help for the plugins commands
  unrankedgui:
    description: permit to open the gui of unranked queue
    permission: xrc.unranked
  rankedgui:
    description: permit to open the gui of ranked queue
    permission: xrc.ranked
